name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: FTP Deploy to Hostinger
    runs-on: ubuntu-latest

    steps:
      # Step 1: Repo code fetch
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: FTP Deploy
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}   # (IP address)
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          server-dir: test-site/
          local-dir: ./

          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            api/config.php
            uploads/**
            database/set-admin-password.php
            .github/**